name: "Update Manifest and Commit Changes"
description: "Checks out the repository, sets up Node, installs dependencies, updates manifest.json, formats, and commits/pushes changes signing the commit."
inputs:
  action:
    description: "Action to perform: publish or delete the artifact branch."
    required: false
    default: "publish"
  manifestPath:
    description: "The path to the manifest.json file."
    required: false
    default: "${{ github.workspace }}/manifest.json"
  schemaPath:
    description: "The path to the plugin settings schema."
    required: false
    default: "${{ github.workspace }}/src/types/plugin-input.ts"
  pluginEntry:
    description: "The path to the plugin entry file."
    required: false
    default: "${{ github.workspace }}/src/index.ts"
  commitMessage:
    description: "The commit message."
    required: false
    default: "chore: [skip ci] updated manifest.json and dist build"
  sourceRef:
    description: "Source branch ref used for short_name and artifact branch mapping."
    required: false
    default: "${{ github.event.workflow_run.head_branch || github.ref_name }}"
  artifactPrefix:
    description: "Prefix used for artifact branches."
    required: false
    default: "dist/"
  nodeVersion:
    description: "The version of Node.js to use."
    default: "24.11.0"
  treatAsEsm:
    description: "If the package is set to be treated as ESM, it will replace __dirname occurrences."
    default: "false"
  bundleSingleFile:
    description: "Bundle plugin entry into a single file (disables code splitting)."
    default: "false"
  sourcemap:
    description: "Generates the sourcemap for the compiled files"
  skipBotEvents:
    description: "Sets manifest.skipBotEvents (true/false)."
    required: false
    default: "true"
  excludeSupportedEvents:
    description: "Comma-separated supported events to remove from generated manifest listeners."
    required: false
    default: ""
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      shell: bash
      run: |
        bun install --frozen-lockfile

    - name: Build project
      if: ${{ inputs.action == 'publish' }}
      shell: bash
      run: |
        echo "Deleting previous dist..."
        rm -rf "${{ github.workspace }}/dist"
        if [ "${{ inputs.bundleSingleFile }}" = "true" ]; then
          echo "Compiling plugin (single file)..."
          bun x esbuild ${{ inputs.pluginEntry }} --bundle --platform=node --format=esm --target=node20 --minify ${{ inputs.sourcemap == 'true' && '--sourcemap' || '' }} --external:./tests --outfile=dist/plugin/index.js
          echo "Compiling plugin types (single file)..."
          bun x esbuild ${{ inputs.schemaPath }} --bundle --platform=node --format=esm --target=node20 --minify --outfile=plugin/index.js
        else
          bun add -DE @vercel/ncc
          echo "Compiling plugin..."
          bun ncc build ${{ inputs.pluginEntry }} --external "./tests" -m ${{ inputs.sourcemap == 'true' && '-s' || '' }} -o dist/plugin
          echo "Compiling plugin types..."
          bun ncc build ${{ inputs.schemaPath }} --external "./tests" -m -o plugin
        fi

    - name: Replace __dirname with import.meta.dirname
      if: ${{ inputs.action == 'publish' && inputs.treatAsEsm }}
      shell: bash
      run: |
        if [ "${{ inputs.treatAsEsm }}" = "true" ]; then
          sed -i 's/__dirname/import.meta.dirname/g' "${{ github.workspace }}/dist/plugin/index.js"
        fi

    - name: Update manifest configuration JSON
      if: ${{ inputs.action == 'publish' }}
      shell: bash
      env:
        MANIFEST_PATH: ${{ inputs.manifestPath }}
        SKIP_BOT_EVENTS: ${{ inputs.skipBotEvents }}
        EXCLUDE_SUPPORTED_EVENTS: ${{ inputs.excludeSupportedEvents }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ inputs.sourceRef }}
      run: |
        node ${{ github.action_path }}/.github/scripts/update-manifest.js

    - name: Format manifest using Prettier
      if: ${{ inputs.action == 'publish' }}
      shell: bash
      run: |
        npx prettier --write manifest.json

    - name: Get GitHub App token
      if: env.APP_ID != '' && env.APP_PRIVATE_KEY != ''
      uses: actions/create-github-app-token@v1
      id: get_installation_token
      with:
        app-id: ${{ env.APP_ID }}
        private-key: ${{ env.APP_PRIVATE_KEY }}

    - name: Install push script dependencies
      shell: bash
      run: |
        echo "Installing dependencies for the push script in ${{ github.action_path }}"
        cd ${{ github.action_path }}
        bun install

    - name: Inject reassembly code into dist/index.js
      if: ${{ inputs.action == 'publish' }}
      shell: bash
      env:
        TREAT_AS_ESM: ${{ inputs.treatAsEsm }}
      run: |
        if [[ "${TREAT_AS_ESM}" == "true" ]]; then
          if [ ! -f dist/plugin/package.json ]; then
            printf '{"type":"module"}\n' > dist/plugin/package.json
          fi
          cp "${{ github.action_path }}/.github/scripts/reassembly-esm.js" dist/index.js
          cp dist/plugin/package.json dist/package.json
        else
          cp "${{ github.action_path }}/.github/scripts/reassembly-cjs.js" dist/index.js
        fi

    - name: Publish manifest.json and dist to artifact branch
      if: ${{ inputs.action == 'publish' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token || github.token }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        COMMIT_MESSAGE: ${{ inputs.commitMessage }}
        MANIFEST_PATH: ${{ inputs.manifestPath }}
        SOURCE_REF: ${{ inputs.sourceRef }}
        ARTIFACT_PREFIX: ${{ inputs.artifactPrefix }}
      run: |
        bun ${{ github.action_path }}/.github/scripts/push-changes.js

    - name: Delete artifact branch
      if: ${{ inputs.action == 'delete' }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ steps.get_installation_token.outputs.token || github.token }}
        SOURCE_REF: ${{ inputs.sourceRef }}
        ARTIFACT_PREFIX: ${{ inputs.artifactPrefix }}
      run: |
        bun ${{ github.action_path }}/.github/scripts/delete-artifact-branch.js
